### ISSUE TITLE
Factorial should have base case 0! = 1

### ISSUE THREAD

**Issue by rofrol** [techmindful/recursive-thinking#1]
https://en.m.wikipedia.org/wiki/Factorial

**Comment by techmindful** [comment]
@rofrol Good point. I'm especially convinced about the reason here: https://math.stackexchange.com/a/20975 The combinatorial example makes sense.

But for people who's just starting to learn factorial, it may not be obvious for why the base case should be `0! = 1`. The common, casual way to introduce factorial is just it's multiplying n, n - 1, n - 2, all the way down to 1. And it makes sense that the base case is `1! = 1`.

Maybe it's good to add a note somewhere, to clarify that the base case is actually `0! = 1`? So the beginners can get into the concept more easily, and on the math side it's rigorous and correct?

**Comment by rofrol** [comment]
Yes. You could add some note that this simplification etc.

**Comment by techmindful** [comment]
Fixed in this commit!
29f9be5d2bdf3a08187e6d916ed38f1afdaa8691
